krenniank/rails-tube-stats-269

Gemfile
Gemfile.lock
app/models/comment.rb
app/models/playlist.rb
app/models/playlist_video.rb
app/models/suggestion.rb
app/models/video.rb
app/models/watch.rb
app/models/watched_video.rb
app/policies/application_policy.rb
db/migrate/20190723084225_create_playlists.rb
db/migrate/20190723092932_create_videos.rb
db/migrate/20190723093258_create_watches.rb
db/migrate/20190723093450_create_playlist_videos.rb
db/migrate/20190723094005_create_suggestions.rb
db/migrate/20190723094838_create_comments.rb
db/migrate/20190723095450_create_watched_videos.rb
db/schema.rb
test/models/comment_test.rb
test/models/playlist_test.rb
test/models/playlist_video_test.rb
test/models/suggestion_test.rb
test/models/video_test.rb
test/models/watch_test.rb
test/models/watched_video_test.rb

Finished our base schema development. Also installed pundit

Schema development

---

app/controllers/application_controller.rb
db/schema.rb

pundit setup

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/controllers/pages_controller.rb
db/schema.rb

stylesheet settings

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb
package.json
yarn.lock

there were some chanhges on json and yarn.lock that im not sure what it means.  can you chekc them to mak esure its ok the changes made?

did google visualr basics

---

app/assets/stylesheets/config/_fonts.scss

Stylesetting

---

db/seeds.rb

did not add creator_id for the playlist

created seeds for playlist and videos

---

app/controllers/pages_controller.rb
config/routes.rb

routes for the home/dashboard and the datapage called data in the controller

added routes for the dashboard and the data-page

---

app/views/pages/dashboard.html.erb
app/views/pages/data.html.erb

created views for the dashboard and data

added views to dashboard and data

---

app/models/comment.rb
app/models/creator.rb
app/models/playlist.rb
app/models/playlist_watcher.rb
app/models/suggestion.rb
app/models/video.rb
app/models/watch.rb
app/models/watched_video.rb
app/models/youtube_account.rb
db/migrate/20190723080112_create_youtube_accounts.rb
db/migrate/20190723080315_create_creators.rb
db/migrate/20190723084225_create_playlists.rb
db/migrate/20190723092932_create_videos.rb
db/migrate/20190723093258_create_watches.rb
db/migrate/20190723094005_create_suggestions.rb
db/migrate/20190723094838_create_comments.rb
db/migrate/20190723123716_remove_password_from_youtube_account.rb
db/migrate/20190723153947_create_playlist_watchers.rb
db/schema.rb
test/models/creator_test.rb
test/models/playlist_watcher_test.rb

DB completed. In our previous iteration, the database would break if someone watched another youtube account that wasn't registered in the database.

Redoing schema

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_login_form.scss
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

created login, 
set up
and forgot password- same structure and style 
do we want the navbar on those pages?

setup for login sign up

---

app/controllers/application_controller.rb
app/views/devise/shared/_links.html.erb
app/views/pages/home.html.erb

added login in the rootpage and some small changes

Fixing signup link

---

app/javascript/packs/application.js
app/views/pages/data.html.erb
app/views/shared/_date_filter.html.erb
db/schema.rb
package.json
yarn.lock

Kyle could u check if its ok, @PaulinaGernandt   i did one element like you said, let me know

date picker

---

app/assets/stylesheets/pages/_data.scss
app/views/shared/_date_filter.html.erb

Can you guys check it our please?
let me know

calendar icon on form

---

app/assets/stylesheets/pages/_dashboard.scss
app/assets/stylesheets/pages/_data.scss
app/controllers/pages_controller.rb
app/views/pages/dashboard.html.erb
app/views/shared/_top3.html.erb

last changes making it work  for the pitch

final change for pitch

---

app/assets/stylesheets/pages/_data.scss
app/views/shared/_date_filter.html.erb

can u guys check it out please?

betterlookin calendar

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

ready for presentation buttons work again

link fixed

---

app/controllers/pages_controller.rb
app/controllers/suggestions_controller.rb
app/views/suggestions/index.html.erb
app/views/suggestions/show.html.erb
config/routes.rb
test/controllers/suggestions_controller_test.rb

rails g controller suggestions index show

created the controller and routes for the suggestions page

---

app/controllers/suggestions_controller.rb
app/views/suggestions/index.html.erb
config/routes.rb
db/schema.rb

didnt create a toggle fixed the bugs

fixed bugs, now its all good

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_dashboard.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/pages_controller.rb
app/controllers/youtube_accounts_controller.rb
app/views/pages/dashboard.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
db/schema.rb
package.json

fixes after merge

---

Gemfile
Gemfile.lock
app/controllers/pages_controller.rb
app/controllers/youtube_accounts_controller.rb
app/models/creator.rb
app/views/shared/_navbar.html.erb

Heroku changes

---

app/controllers/youtube_accounts_controller.rb
app/models/youtube_account.rb
app/views/pages/dashboard.html.erb
app/views/shared/_navbar.html.erb
app/views/youtube_accounts/new.html.erb
config/routes.rb

fixed the routing problem

---

app/views/pages/home.html.erb

Display links only if user is not logged in

fix links on homepage

---

app/controllers/pages_controller.rb
app/models/video.rb
app/models/watch.rb
app/models/youtube_account.rb
app/views/pages/data.html.erb
app/views/shared/_sankey.html.erb

Implemented the sankey to be broken down by category

Sankey implementation

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_slider.scss
app/assets/stylesheets/components/_table.scss
app/assets/stylesheets/pages/_dashboard.scss
app/assets/stylesheets/pages/_data.scss
app/views/pages/dashboard.html.erb
app/views/pages/data.html.erb
app/views/shared/_top3.html.erb

veeery careful with the merges pls :DD

everything
